// c:\Projects\coore\lib\src\platform\service.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'platform_service_impl.dart';
export 'platform_service_interface.dart';
