// c:\Projects\coore\lib\src\localization.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'cubit/cubit.dart';
export 'widget/widget.dart';
